/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CobranzaRouteImport } from './routes/cobranza'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesNuevoRouteImport } from './routes/clientes.nuevo'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'

const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CobranzaRoute = CobranzaRouteImport.update({
  id: '/cobranza',
  path: '/cobranza',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNuevoRoute = ClientesNuevoRouteImport.update({
  id: '/clientes/nuevo',
  path: '/clientes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/rutas': typeof RutasRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/rutas': typeof RutasRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/rutas': typeof RutasRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/rutas'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/rutas'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/rutas'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CobranzaRoute: typeof CobranzaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CreditosRoute: typeof CreditosRoute
  RutasRoute: typeof RutasRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ClientesNuevoRoute: typeof ClientesNuevoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranza': {
      id: '/cobranza'
      path: '/cobranza'
      fullPath: '/cobranza'
      preLoaderRoute: typeof CobranzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/nuevo': {
      id: '/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof ClientesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CobranzaRoute: CobranzaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CreditosRoute: CreditosRoute,
  RutasRoute: RutasRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ClientesNuevoRoute: ClientesNuevoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
