/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as NuevaVentaRouteImport } from './routes/nueva-venta'
import { Route as MigracionRouteImport } from './routes/migracion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstadoCuentaRouteImport } from './routes/estado-cuenta'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CobranzaRouteImport } from './routes/cobranza'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ConfiguracionMoraRouteImport } from './routes/configuracion_.mora'
import { Route as CobranzaAprobacionRouteImport } from './routes/cobranza_.aprobacion'
import { Route as ClientesNuevoRouteImport } from './routes/clientes.nuevo'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaVentaRoute = NuevaVentaRouteImport.update({
  id: '/nueva-venta',
  path: '/nueva-venta',
  getParentRoute: () => rootRouteImport,
} as any)
const MigracionRoute = MigracionRouteImport.update({
  id: '/migracion',
  path: '/migracion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoCuentaRoute = EstadoCuentaRouteImport.update({
  id: '/estado-cuenta',
  path: '/estado-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CobranzaRoute = CobranzaRouteImport.update({
  id: '/cobranza',
  path: '/cobranza',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionMoraRoute = ConfiguracionMoraRouteImport.update({
  id: '/configuracion_/mora',
  path: '/configuracion/mora',
  getParentRoute: () => rootRouteImport,
} as any)
const CobranzaAprobacionRoute = CobranzaAprobacionRouteImport.update({
  id: '/cobranza_/aprobacion',
  path: '/cobranza/aprobacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNuevoRoute = ClientesNuevoRouteImport.update({
  id: '/clientes/nuevo',
  path: '/clientes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/estado-cuenta': typeof EstadoCuentaRoute
  '/login': typeof LoginRoute
  '/migracion': typeof MigracionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/rutas': typeof RutasRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/cobranza/aprobacion': typeof CobranzaAprobacionRoute
  '/configuracion/mora': typeof ConfiguracionMoraRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/estado-cuenta': typeof EstadoCuentaRoute
  '/login': typeof LoginRoute
  '/migracion': typeof MigracionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/rutas': typeof RutasRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/cobranza/aprobacion': typeof CobranzaAprobacionRoute
  '/configuracion/mora': typeof ConfiguracionMoraRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/estado-cuenta': typeof EstadoCuentaRoute
  '/login': typeof LoginRoute
  '/migracion': typeof MigracionRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/rutas': typeof RutasRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
  '/cobranza_/aprobacion': typeof CobranzaAprobacionRoute
  '/configuracion_/mora': typeof ConfiguracionMoraRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/estado-cuenta'
    | '/login'
    | '/migracion'
    | '/nueva-venta'
    | '/productos'
    | '/rutas'
    | '/usuarios'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/cobranza/aprobacion'
    | '/configuracion/mora'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/estado-cuenta'
    | '/login'
    | '/migracion'
    | '/nueva-venta'
    | '/productos'
    | '/rutas'
    | '/usuarios'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/cobranza/aprobacion'
    | '/configuracion/mora'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/estado-cuenta'
    | '/login'
    | '/migracion'
    | '/nueva-venta'
    | '/productos'
    | '/rutas'
    | '/usuarios'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/cobranza_/aprobacion'
    | '/configuracion_/mora'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CobranzaRoute: typeof CobranzaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CreditosRoute: typeof CreditosRoute
  EstadoCuentaRoute: typeof EstadoCuentaRoute
  LoginRoute: typeof LoginRoute
  MigracionRoute: typeof MigracionRoute
  NuevaVentaRoute: typeof NuevaVentaRoute
  ProductosRoute: typeof ProductosRoute
  RutasRoute: typeof RutasRoute
  UsuariosRoute: typeof UsuariosRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ClientesNuevoRoute: typeof ClientesNuevoRoute
  CobranzaAprobacionRoute: typeof CobranzaAprobacionRoute
  ConfiguracionMoraRoute: typeof ConfiguracionMoraRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-venta': {
      id: '/nueva-venta'
      path: '/nueva-venta'
      fullPath: '/nueva-venta'
      preLoaderRoute: typeof NuevaVentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migracion': {
      id: '/migracion'
      path: '/migracion'
      fullPath: '/migracion'
      preLoaderRoute: typeof MigracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado-cuenta': {
      id: '/estado-cuenta'
      path: '/estado-cuenta'
      fullPath: '/estado-cuenta'
      preLoaderRoute: typeof EstadoCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranza': {
      id: '/cobranza'
      path: '/cobranza'
      fullPath: '/cobranza'
      preLoaderRoute: typeof CobranzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion_/mora': {
      id: '/configuracion_/mora'
      path: '/configuracion/mora'
      fullPath: '/configuracion/mora'
      preLoaderRoute: typeof ConfiguracionMoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranza_/aprobacion': {
      id: '/cobranza_/aprobacion'
      path: '/cobranza/aprobacion'
      fullPath: '/cobranza/aprobacion'
      preLoaderRoute: typeof CobranzaAprobacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/nuevo': {
      id: '/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof ClientesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CobranzaRoute: CobranzaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CreditosRoute: CreditosRoute,
  EstadoCuentaRoute: EstadoCuentaRoute,
  LoginRoute: LoginRoute,
  MigracionRoute: MigracionRoute,
  NuevaVentaRoute: NuevaVentaRoute,
  ProductosRoute: ProductosRoute,
  RutasRoute: RutasRoute,
  UsuariosRoute: UsuariosRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ClientesNuevoRoute: ClientesNuevoRoute,
  CobranzaAprobacionRoute: CobranzaAprobacionRoute,
  ConfiguracionMoraRoute: ConfiguracionMoraRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
