/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CobranzaRouteImport } from './routes/cobranza'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesNuevoRouteImport } from './routes/clientes.nuevo'

const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CobranzaRoute = CobranzaRouteImport.update({
  id: '/cobranza',
  path: '/cobranza',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNuevoRoute = ClientesNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/rutas': typeof RutasRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/rutas': typeof RutasRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cobranza': typeof CobranzaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/creditos': typeof CreditosRoute
  '/rutas': typeof RutasRoute
  '/clientes/nuevo': typeof ClientesNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/rutas'
    | '/clientes/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/rutas'
    | '/clientes/nuevo'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/cobranza'
    | '/configuracion'
    | '/creditos'
    | '/rutas'
    | '/clientes/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  CobranzaRoute: typeof CobranzaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CreditosRoute: typeof CreditosRoute
  RutasRoute: typeof RutasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranza': {
      id: '/cobranza'
      path: '/cobranza'
      fullPath: '/cobranza'
      preLoaderRoute: typeof CobranzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/nuevo': {
      id: '/clientes/nuevo'
      path: '/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof ClientesNuevoRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesNuevoRoute: typeof ClientesNuevoRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesNuevoRoute: ClientesNuevoRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  CobranzaRoute: CobranzaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CreditosRoute: CreditosRoute,
  RutasRoute: RutasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
